

CREATE DATABASE ATV2;
USE ATV2;


CREATE  TABLE PRODUTO(
  ID			  INTEGER not NULL PRIMARY KEY,
  DESCRICAO		  VARCHAR(30), 
  QUANT			  DECIMAL(9,3),
  VALOR 		  DECIMAL(5,2),
  QT_MINIMA		  DECIMAL(9,3),
  PERECIVEL		  BOOLEAN
);



CREATE TABLE  ENTRADA(
  ID 			INTEGER NOT NULL PRIMARY KEY,
  DT_ENTRADA 		DATE,
  QT_ENTRADA 		DECIMAL(9,3),
  PRODUTO_ID 		INTEGER,
  FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID)
);



CREATE TABLE  SAIDA(
  ID            INTEGER NOT NULL PRIMARY KEY,
  DT_SAIDA      DATE,
  QT_SAIDA      DECIMAL(9,3),
  SAIDACOL      VARCHAR(45),
  PRODUTO_ID    INTEGER,
  FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID)
);



CREATE TABLE  LOTE(
  ID 			INTEGER NOT NULL PRIMARY KEY,
  DT_VENCIMENTO 	DATE,
  NUM_LOTE 		VARCHAR(20),
  QT_LOTE 		DECIMAL(9,3),
  LOTECOL 		VARCHAR(45),
  PRODUTO_ID 		INTEGER,
  FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID)
);



CREATE TABLE UF(
  ID 	            INTEGER NOT NULL PRIMARY KEY,
  NOME		    VARCHAR(20),
  SIGLA		    VARCHAR(2)
);



CREATE TABLE MUNICIPIO(
  ID 			INTEGER NOT NULL PRIMARY KEY,
  NOME 		    	VARCHAR(20),
  UF_ID 		INTEGER,
  FOREIGN KEY (UF_ID) REFERENCES UF(ID)
);



CREATE TABLE CLIENTE(
  ID 		          INTEGER NOT NULL PRIMARY KEY,
  NOME		          VARCHAR(50),
  LOGRADOURO		  VARCHAR(30),
  NUMERO	          VARCHAR(6),
  BAIRRO	          VARCHAR(20),
  MUNICIPIO_ID 		INTEGER,
  MUNICIPIO_UF_ID	INTEGER,
  FOREIGN KEY (MUNICIPIO_ID) REFERENCES MUNICIPIO(ID),
  FOREIGN KEY (MUNICIPIO_UF_ID) REFERENCES MUNICIPIO(UF_ID)
);



CREATE TABLE TELEFONE(
  ID				  INTEGER NOT NULL PRIMARY KEY,
  TEELFONE			  VARCHAR(15),
  CLIENTE_ID			INTEGER,
  CLIENTE_MUNICIPIO_ID		INTEGER,
  CLIENTE_MUNICIPIO_UF_ID	INTEGER,
  FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID),
  FOREIGN KEY (CLIENTE_MUNICIPIO_ID) REFERENCES CLIENTE(MUNICIPIO_ID),
  FOREIGN KEY (CLIENTE_MUNICIPIO_UF_ID) REFERENCES CLIENTE(MUNICIPIO_UF_ID)
);



CREATE TABLE TIPO_PAGTO(
  ID			    INTEGER NOT NULL PRIMARY KEY,
  TIPO_PAGTO	    VARCHAR(20)
);



CREATE TABLE VENDA(
  ID		          INTEGER NOT NULL PRIMARY KEY,
  DT_VENDA	      DATE,
  TIPO_PAGTO_ID 	INTEGER, 
  CLIENTE_ID	    INTEGER,
  FOREIGN KEY (TIPO_PAGTO_ID) REFERENCES TIPO_PAGTO(ID),
  FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
);



CREATE TABLE ITEM_VENDA(
  VENDA_ID		    INTEGER,
  PRODUTO_ID	    INTEGER,
  QT_ITEM		      DECIMAL(9,3),
  VR_ITEM		      DECIMAL(9,3),
  FOREIGN KEY (VENDA_ID) REFERENCES VENDA(ID),
  FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID)
);



CREATE TABLE DOCUMENTO(
  ID					            INTEGER NOT NULL PRIMARY KEY,
  VR_DOCUMENTO		      	DECIMAL(5, 2),
  DT_VENC 				        DATE,
  VENDA_ID				        INTEGER,
  VENDA_TIPO_PAGTO_ID			INTEGER,
  CLIENTE_ID				      INTEGER,
  FOREIGN KEY (VENDA_ID) REFERENCES VENDA(ID),
  FOREIGN KEY (VENDA_TIPO_PAGTO_ID) REFERENCES VENDA(TIPO_PAGTO_ID),
  FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
);


