DROP DATABASE IF EXISTS prova;

CREATE DATABASE IF NOT EXISTS prova;
USE prova;

CREATE TABLE IF NOT EXISTS VENDAS(
IDVENDAS INTEGER NOT NULL PRIMARY KEY,
ID_NF INTEGER,
ID_ITEM INTEGER,
COD_PROD INTEGER,
VALOR_UNIT DECIMAL(10,2),
QUANTIDADE INTEGER,
DESCONTO DECIMAL(10,2)
);

INSERT INTO VENDAS (IDVENDAS, ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (1,1,1,1,25,10,5);
INSERT INTO VENDAS (IDVENDAS, ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (2,1,2,2,13.50,3, null);
INSERT INTO VENDAS (IDVENDAS, ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (3,1,3,3,15,2, null);
INSERT INTO VENDAS (IDVENDAS, ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (4,1,4,4,10,1, null);
INSERT INTO VENDAS (IDVENDAS, ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (5,1,5,5,30,1, null);
INSERT INTO VENDAS (IDVENDAS, ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (6,2,1,3,15,4, null);
INSERT INTO VENDAS (IDVENDAS, ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (7,2,2,4,10,5, null);
INSERT INTO VENDAS (IDVENDAS, ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (8,2,3,5,30,7, null);
INSERT INTO VENDAS (IDVENDAS, ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (9,3,1,1,25,5, null);
INSERT INTO VENDAS (IDVENDAS, ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (10,3,2,4,10,4, null);
INSERT INTO VENDAS (IDVENDAS, ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (11,3,3,5,30,5, null);
INSERT INTO VENDAS (IDVENDAS, ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (12,3,4,2,13.50,7, null);
INSERT INTO VENDAS (IDVENDAS, ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (13,4,1,5,30,10,15);
INSERT INTO VENDAS (IDVENDAS, ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (14,4,2,4,10,12,5);
INSERT INTO VENDAS (IDVENDAS, ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (15,4,3,1,25,13,5);
INSERT INTO VENDAS (IDVENDAS, ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (16,4,4,2,13.50,15,5);
INSERT INTO VENDAS (IDVENDAS, ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (17,5,1,3,15,3, null);
INSERT INTO VENDAS (IDVENDAS, ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (18,5,2,5,30,6, null);
INSERT INTO VENDAS (IDVENDAS, ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (19,6,1,1,25,22,15);
INSERT INTO VENDAS (IDVENDAS, ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (20,6,2,3,15,25,20);
INSERT INTO VENDAS (IDVENDAS, ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (21,7,1,1,25,10,3);
INSERT INTO VENDAS (IDVENDAS, ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (22,7,2,2,13.50,10,4);
INSERT INTO VENDAS (IDVENDAS, ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (23,7,3,3,15,10,4);
INSERT INTO VENDAS (IDVENDAS, ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES (24,7,4,5,30,10,1);

/* 1 - Pesquise os itens que foram vendidos sem desconto. As colunas presentes no resultado da
consulta são: ID_NF, ID_ITEM, COD_PROD E VALOR_UNIT. */

SELECT ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT 
FROM VENDAS 
WHERE DESCONTO IS NULL;


/* 2 - Pesquise os itens que foram vendidos com desconto. As colunas presentes no resultado da
consulta são: ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT E O VALOR VENDIDO. OBS: O valor
vendido é igual ao VALOR_UNIT - (VALOR_UNIT*(DESCONTO/100)). */

SELECT ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, VALOR_UNIT - (VALOR_UNIT*(DESCONTO/100)) AS VALOR_VENDIDO
FROM VENDAS 
WHERE DESCONTO IS NOT NULL;

/* 3 - Altere o valor do desconto (para zero) de todos os registros onde este campo é nulo. */

UPDATE VENDAS
SET DESCONTO = 0
WHERE DESCONTO IS NULL;


/* 4 - Pesquise os itens que foram vendidos. As colunas presentes no resultado da consulta são:
ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, VALOR_TOTAL, DESCONTO, VALOR_VENDIDO. OBS: O
VALOR_TOTAL é obtido pela fórmula: QUANTIDADE * VALOR_UNIT. O VALOR_VENDIDO é igual a
VALOR_UNIT - (VALOR_UNIT*(DESCONTO/100)). */

SELECT ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE * VALOR_UNIT AS VALOR_TOTAL, DESCONTO, VALOR_UNIT - (VALOR_UNIT*(DESCONTO/100)) AS VALOR_VENDIDO 
FROM VENDAS;







